# SPDX-License-Identifier: GPL-2.0-only

FROM debian:13-slim

COPY root/ /

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential ca-certificates git meson ninja-build pkg-config python3 \
        python3-pip \
        libtraceevent-dev libsqlite3-dev sqlite3 libpci-dev python3-sqlalchemy \
        libglib2.0-0 libpixman-1-0 zlib1g libslirp0 libcap-ng0 libaio1t64 \
        liburing2 libseccomp2 libfdt1 libgnutls30t64 libudev1 \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages --no-cache-dir \
        qmp /opt/qemu/libexec/rasdaemon/qemu_qmp-*.whl

COPY rasdaemon-ci/ /opt/rasdaemon-ci/
COPY rasdaemon-ci.py /usr/local/bin/rasdaemon-ci

ENV PATH="/opt/qemu/bin:${PATH}"
ENTRYPOINT ["/usr/local/bin/rasdaemon-ci"]
